from solidgpt.src.orchestration.orchestration import *


orchestration = Orchestration()
orchestration.add_graph("config/config_data.json", "Basic Graph")
orchestration.add_graph("config/example.json", "Graph Generated by frontend")
orchestration.show_graphs()

orchestration.remove_graph(1)
orchestration.show_graphs()

orchestration.remove_all_graphs()
orchestration.show_graphs()
