"""Agent Names"""
AGENT_NAME_SOFTWARE_DEVELOPER = "Software Developer"
AGENT_NAME_PRINCIPAL_ENGINEER = "Principal Engineer"
AGENT_NAME_PRODUCT_MANAGER = "Product Manager"
AGENT_NAME_CUSTOM_AGENT = "Custom Agent"

"""Skill Names"""
SKILL_NAME_DEBUG_CODE = "Debug Code"
SKILL_NAME_WRITE_CODE = "Write Code"
SKILL_NAME_WRITE_PRODUCT_REQUIREMENTS_DOCUMENTATION = "Write Product Requirement Documentation"
SKILL_NAME_USE_NOTION = "Use Notion"
SKILL_NAME_WRITE_HLD = "Write High Level Design"
SKILL_NAME_CREATE_KANBAN_BOARD = "Create Kanban Board"
SKILL_NAME_CUSTOM_SKILL = "Custom Skill"
SKILL_NAME_WRITE_YAML = "Write lowdefy YAML"
