# Use an official Python runtime as the parent image
FROM python:3.11.5-bullseye

# Set the working directory in the container to /app
WORKDIR /app

# Copy the current directory (where the Dockerfile is) into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

CMD export PYTHONPATH=$PYTHONPATH:$(git rev-parse --show-toplevel)/ && celery -A solidgpt.src.api.celery_tasks worker --loglevel=info