# Use an official Node.js runtime as the parent image
FROM node:latest

# Set the working directory in the container to /app
WORKDIR /app
COPY . /app

# Change directory to solidportal/panel
WORKDIR /app/solidportal/panel

# Copy the current directory (where the Dockerfile is) into the container at /app

# Install any needed packages specified in package.json
RUN npm install

# Start the application
CMD ["npm", "start"]
