service: serverless-telegram-bot

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  profile: ckl
  environment:
    TELEGRAM_TOKEN: ${file(./serverless.env.yml):TELEGRAM_TOKEN, ''}

functions:
  webhook:
    handler: handler.webhook
    events:
      - httpApi:
          path: /
          method: POST

  set_webhook:
    handler: handler.set_webhook
    events:
      - httpApi:
          path: /set_webhook
          method: POST

plugins:
  - serverless-python-requirements
