"""Skill Names"""
SKILL_NAME_WRITE_PRODUCT_REQUIREMENTS_DOCUMENTATION = "Write Product Requirement Documentation"
SKILL_NAME_WRITE_HLD = "Write High Level Design"
SKILL_NAME_CREATE_KANBAN_BOARD = "Create Kanban Board"
SKILL_NAME_CUSTOM_SKILL = "Custom Skill"
SKILL_NAME_WRITE_YAML = "Write lowdefy YAML"
SKILL_NAME_RUN_APP = "Host and run web app"
SKILL_NAME_LOAD_REPO = "Load repo"
SKILL_NAME_SUMMARY_CODE = "Summary code"
