"""Skill Names"""
SKILL_NAME_WRITE_PRODUCT_REQUIREMENTS_DOCUMENTATION = "Write Product Requirement Documentation"
SKILL_NAME_WRITE_HLD = "Write High Level Design"
SKILL_NAME_CREATE_KANBAN_BOARD = "Create Kanban Board"
SKILL_NAME_CUSTOM_SKILL = "Custom Skill"
SKILL_NAME_WRITE_YAML = "Write lowdefy YAML"
SKILL_NAME_RUN_APP = "Host and run web app"
SKILL_NAME_ANALYSIS_PRODUCT = "Analysis Product"
SKILL_NAME_PROVIDE_TECH_SOLUTION = "Provide Technical Solution"